
apiVersion: v1
kind: Namespace
metadata:
  name: clickhouse-db
---
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: analytic-db
  namespace: clickhouse-db
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume
      serviceTemplate: service-nodeport
  
  configuration:
    users:
      admin/password: "admin123"
      admin/networks/ip: "0.0.0.0/0"
      admin/profile: default
      
      dbt_user/password: "dbtpass"
      dbt_user/networks/ip: "0.0.0.0/0"
      dbt_user/profile: default

    clusters:
      - name: "development"
        layout:
          shardsCount: 1
          replicasCount: 1
  
  templates:
    volumeClaimTemplates:
      - name: data-volume
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: local-path
          resources:
            requests:
              storage: 10Gi

    serviceTemplates:
      - name: service-nodeport
        spec:
          type: NodePort
          ports:
            - name: http
              port: 8123
              nodePort: 30123
            - name: tcp
              port: 9000
              nodePort: 30900